### ISSUE TITLE
"found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target"

### ISSUE THREAD

**Issue by mattyoung** [kylehughes/RomanNumeralKit#14]
Xcode show this warning...

"~/Library/Developer/Xcode/DerivedData/RomanNumeralCodeGen-fmcsyogevbkmgyfqrwouonytphww/SourcePackages/checkouts/RomanNumeralKit/Sources/RomanNumeralKit/Info.plist
"

**Comment by kylehughes** [comment]
I apologize for not seeing this sooner. No one has ever submitted an issue before 😅

Thank you for bringing this to my attention. I will address it.

**Comment by kylehughes** [comment]
Fixed in 1.2.1.

Thanks again.
